"""followers

Revision ID: 92604a70c02f
Revises: 7e8cb8f4b3af
Create Date: 2018-08-18 17:29:54.502042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92604a70c02f'
down_revision = '7e8cb8f4b3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
